// Pure evaluated datasets with zero external references
window.PANDALS_DATA = [
  {
    "id": "P0011",
    "rank": 1,
    "name": "Lalbaugcha Raja",
    "area": "Lalbaug",
    "address": "Shree Ganesh Nagar, Dr Babasaheb Ambedkar Road, Lalbaug Market, Mumbai 400012",
    "lat": 18.9908,
    "lng": 72.8367,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Venue-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti: ~7 AM | 12-1 PM | 7 PM | 10 PM",
    "timingDetails": "Unofficial aarti times: morning ~7:00-7:15 AM, midday ~12:00-1:00 PM, evening ~7:00-7:15 PM, and night ~10:00-10:30 PM. Sources vary slightly; confirm on lalbaugcharaja.com nearer the date.",
    "sourceLine": "Current source verifies the venue for 2026.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Lalbaugcha%20Raja%2C%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0012",
    "rank": 2,
    "name": "Mumbaicha Raja (Ganesh Galli)",
    "area": "Lalbaug",
    "address": "Lalbaug Sarvajanik Utsav Mandal, Ganesh Galli, Lalbaug, Mumbai 400012",
    "lat": 18.9942,
    "lng": 72.8373,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Street-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti unpublished | Darshan 9 AM-3 PM",
    "timingDetails": "Specific aarti time is not published. General darshan window: 9 AM-3 PM.",
    "sourceLine": "Street-level estimate. Check the exact entrance before walking.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Mumbaicha%20Raja%20Ganesh%20Galli%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0010",
    "rank": 3,
    "name": "GSB Seva Mandal",
    "area": "King's Circle",
    "address": "Shree Sukriteendra Nagar, King's Circle, Mumbai",
    "lat": 19.0288,
    "lng": 72.8569,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Venue-area estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti unpublished | Darshan 6 AM-11 PM",
    "timingDetails": "Specific aarti time is not published. General darshan window: 6 AM-11 PM.",
    "sourceLine": "Venue-area estimate. Check the exact entrance before walking.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=GSB%20Seva%20Mandal%20Kings%20Circle%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0001",
    "rank": 4,
    "name": "Andhericha Raja",
    "area": "Andheri West",
    "address": "Azad Nagar Sarvajanik Utsav Samiti, Veera Desai Road, Andheri West, Mumbai 400053",
    "lat": 19.13,
    "lng": 72.83688,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Venue-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti unpublished | Darshan 5 AM-12 PM",
    "timingDetails": "Specific aarti time is not published. Best darshan window: 5 AM-12 PM.",
    "sourceLine": "Current source verifies the venue for 2026.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Andhericha%20Raja%20Veera%20Desai%20Road%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0002",
    "rank": 5,
    "name": "Chinchpoklicha Chintamani",
    "area": "Chinchpokli",
    "address": "Dattaram Lad Marg, Chinchpokli East, Mumbai",
    "lat": 18.9872,
    "lng": 72.8337,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Street-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Evening aarti | Darshan 10 AM-9 PM",
    "timingDetails": "Aarti is held in the evening, but the exact time is not published. General visiting window: 10 AM-9 PM.",
    "sourceLine": "Street-level estimate. Check the exact entrance before walking.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Chinchpoklicha%20Chintamani%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0005",
    "rank": 6,
    "name": "Girgaoncha Raja",
    "area": "Girgaon",
    "address": "Nikadwari Lane, Girgaon, Mumbai",
    "lat": 18.9553,
    "lng": 72.8167,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Lane-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti unpublished | Visiting 9 AM-6 PM",
    "timingDetails": "Specific aarti time is not published. General visiting window: 9 AM-6 PM.",
    "sourceLine": "Lane-level estimate. Check the exact entrance before walking.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Girgaoncha%20Raja%20Nikadwari%20Lane%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0008",
    "rank": 7,
    "name": "Khetwadicha Ganraj",
    "area": "Khetwadi",
    "address": "Khetwadi 12th Lane, Girgaon, Mumbai 400004",
    "lat": 18.960512,
    "lng": 72.821283,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Street-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti unpublished | Open during the day",
    "timingDetails": "Specific aarti time is not published. Visiting is described only as during the day.",
    "sourceLine": "Current source verifies the venue for 2026.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Khetwadicha%20Ganraj%2012th%20Lane%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0006",
    "rank": 8,
    "name": "Keshavji Naik Chawl Ganpati",
    "area": "Girgaon",
    "address": "Keshavji Naik Chawl, Gokhale Path, Girgaon, Mumbai 400004",
    "lat": 18.954172,
    "lng": 72.821953,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Building-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti unpublished | Open any time of day",
    "timingDetails": "Specific aarti time is not published. The pandal is described as open any time of the day.",
    "sourceLine": "Current source verifies the venue for 2026.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Keshavji%20Naik%20Chawl%20Ganpati%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0007",
    "rank": 9,
    "name": "Malabar Hill Cha Raja",
    "area": "Grant Road West",
    "address": "Ganesh Chowk, Bhaji Galli, Shankar Sheth Road, Grant Road West, Mumbai 400007",
    "lat": 18.9632,
    "lng": 72.8197,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Street-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti: 8 AM | 8 PM daily",
    "timingDetails": "The mandal's official 2026 site lists daily Maha Aarti at 8 AM and 8 PM.",
    "sourceLine": "Street-level estimate. Check the exact entrance before walking.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Malabar%20Hill%20Cha%20Raja%20Grant%20Road%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0004",
    "rank": 10,
    "name": "Fortcha Raja",
    "area": "Fort / Ballard Estate",
    "address": "Ballard Estate, Fort, Mumbai",
    "lat": 18.9355,
    "lng": 72.8385,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Neighbourhood estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "No aarti or darshan timing was found published online.",
    "sourceLine": "Neighbourhood estimate. Confirm the exact venue before walking.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Fortcha%20Raja%20Ballard%20Estate%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0013",
    "rank": 11,
    "name": "Raja Tejukayacha",
    "area": "Lalbaug",
    "address": "Tejukaya Mansion, Dr Babasaheb Ambedkar Road, Lalbaug, Mumbai 400012",
    "lat": 18.994101,
    "lng": 72.835795,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Building-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Daily kakad, madhyan, evening, and shej aarti times were not published in the sources checked. Check the mandal's official channels closer to the date.",
    "sourceLine": "Current 2026 reporting verifies the mandal and venue.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Raja%20Tejukayacha%20Lalbaug%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0014",
    "rank": 12,
    "name": "Parel Cha Raja",
    "area": "Parel East",
    "address": "Bhivajirao Nare Udyan, Nare Park, Parel East, Mumbai 400012",
    "lat": 18.99975,
    "lng": 72.83895,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Venue-area estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact 2026 aarti times were not published on the mandal's official site. Check its official Instagram or Facebook closer to the date.",
    "sourceLine": "Current source verifies Nare Park; confirm the queue entrance.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Parel%20Cha%20Raja%20Nare%20Park%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0015",
    "rank": 13,
    "name": "Kalachowkicha Mahaganpati",
    "area": "Kalachowki",
    "address": "Swapnapurti A-33, Digvijay Gruha Sankul, Dattaram Lad Marg, Kalachowki, Mumbai 400033",
    "lat": 18.98801,
    "lng": 72.837345,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Venue-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact 2026 kakad, madhyan, evening, and shej aarti times were not published. Check the mandal's official social channels closer to the date.",
    "sourceLine": "Current 2026 source and mapped venue agree on this pin.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Kalachowkicha%20Mahaganpati%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0016",
    "rank": 14,
    "name": "Chandanwadi Cha God Ganpati",
    "area": "Chandanwadi / Marine Lines",
    "address": "69/71 Yashwant Chawl, Chandanwadi Road, Marine Lines, Mumbai 400002",
    "lat": 18.945635,
    "lng": 72.825235,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Building-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "The 2026 arrival aarti at Thakurdwar was announced for 23 August at 6:30 PM, but a daily festival aarti schedule was not published. Check the official mandal page closer to the date.",
    "sourceLine": "Current 2026 mandal updates verify this venue.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Akhil%20Chandanwadi%20Sarvajanik%20Ganeshotsav%20Mandal%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0017",
    "rank": 15,
    "name": "Dongri Cha Raja",
    "area": "Dongri / Umerkhadi",
    "address": "Ganesh Chowk, Dr Maheshwari Road, Sandhurst Road Station West, Dongri, Mumbai 400009",
    "lat": 18.960333,
    "lng": 72.839107,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Venue-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "An evening aarti is reported, but an exact 2026 time was not published. Check the mandal social channels closer to the date.",
    "sourceLine": "Current reporting and the mapped venue agree on this pin.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Dongri%20Cha%20Raja%20Ganesh%20Chowk%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0018",
    "rank": 16,
    "name": "GSB Ganpati Wadala",
    "area": "Wadala",
    "address": "Dwarakanath Bhavan, Shree Ram Mandir Complex, Katrak Road, Wadala, Mumbai 400031",
    "lat": 19.015995,
    "lng": 72.851724,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Venue-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti not listed | Poojas 7 AM-9 PM",
    "timingDetails": "The official 2026 schedule lists Ganahoma from 7 AM, Mahapooja at 1 PM, Deeparadhana at 6:30 PM, Pushpa Pooja at 7 PM, and Ratri Pooja at 9 PM. It does not separately label daily aarti times.",
    "sourceLine": "Official 2026 sources verify the venue and worship schedule.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=GSB%20Ganpati%20Wadala%20Shree%20Ram%20Mandir",
    "source": "official"
  },
  {
    "id": "P0019",
    "rank": 17,
    "name": "Sahyadri Krida Mandal",
    "area": "Tilak Nagar, Chembur",
    "address": "Tilak Nagar Municipal Ground, Sahyadri Garden, Road 12, Chembur West, Mumbai 400089",
    "lat": 19.06926,
    "lng": 72.89787,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Ground-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact 2026 aarti times were not published in the sources checked. Check the mandal's official social channels closer to the date.",
    "sourceLine": "Current 2026 sources verify the mandal at this ground.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Sahyadri%20Krida%20Mandal%20Tilak%20Nagar%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0020",
    "rank": 18,
    "name": "Mumbai Cha Peshwa",
    "area": "Vile Parle East",
    "address": "Mumbai Cha Peshwa Pandal, Shraddhanand Road, Vile Parle East, Mumbai 400057",
    "lat": 19.093641,
    "lng": 72.844971,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Venue-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact 2026 aarti times were not published. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Current 2026 arrival coverage and mapped venue agree.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Mumbai%20Cha%20Peshwa%20Vile%20Parle%20East",
    "source": "official"
  },
  {
    "id": "P0021",
    "rank": 19,
    "name": "Ghatkopar Cha Raja",
    "area": "Ghatkopar East",
    "address": "159/61, Laxminarayan Lane, opposite Gandhi Market, M G Road, Ghatkopar East, Mumbai 400077",
    "lat": 19.080522,
    "lng": 72.904399,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Building-level",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact 2026 aarti times were not published in the sources checked. Check the mandal's official Facebook page closer to the date.",
    "sourceLine": "The registered mandal address resolves to this building-level pin.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Ghatkopar%20Cha%20Raja%20Laxminarayan%20Lane%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0022",
    "rank": 20,
    "name": "Sanpadyacha Maharaja",
    "area": "Sanpada, Navi Mumbai",
    "address": "B-51, St Nirankari Marg, Sector 10, Sanpada, Navi Mumbai 400705",
    "lat": 19.0634,
    "lng": 73.0125,
    "status": "editor_verified",
    "confidence": "exact",
    "pinPrecision": "Official exact pin",
    "evidenceYear": 2026,
    "aarti_times": "Aarti: 7 AM | 8 PM daily",
    "timingDetails": "The mandal's official 2026 site lists daily aarti at 7 AM and 8 PM.",
    "sourceLine": "Official 2026 site verifies the venue and exact map pin.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.0634%2C73.0125",
    "source": "official"
  },
  {
    "id": "P0023",
    "rank": 21,
    "name": "Tejukaya Sarvajanik Ganeshotsav Mandal",
    "area": "Lalbaug",
    "address": "Lalbaug, Mumbai, Maharashtra 400011",
    "lat": 18.9914237,
    "lng": 72.8364587,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Tejukaya%20Sarvajanik%20Ganeshotsav%20Mandal%20Lalbaug%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0024",
    "rank": 22,
    "name": "Parel Sarvajanik Utsav Mandal (Parelcha Raja)",
    "area": "Nare Park, Parel",
    "address": "Nare Park, Lalbaug, Mumbai, Maharashtra 400033",
    "lat": 18.9997574,
    "lng": 72.8389491,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Parel%20Sarvajanik%20Utsav%20Mandal%20Nare%20Park%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0025",
    "rank": 23,
    "name": "Khetwadi 11th Galli Mandal (Mumbaicha Maharaja)",
    "area": "Khetwadi 11th Lane",
    "address": "Khetwadi 11th Lane, Girgaon, Mumbai, Maharashtra 400004",
    "lat": 18.9596275,
    "lng": 72.8213699,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Khetwadi%2011th%20Galli%20Mandal%20Mumbaicha%20Maharaja%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0026",
    "rank": 24,
    "name": "Sahyadri Krida Mandal",
    "area": "Tilak Nagar, Chembur",
    "address": "Tilak Nagar, Chembur, Mumbai, Maharashtra 400089",
    "lat": 19.0692377,
    "lng": 72.8978464,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Sahyadri%20Krida%20Mandal%20Tilak%20Nagar%20Chembur%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0027",
    "rank": 25,
    "name": "Jolly Boys Sarvajanik Ganesh Mandal",
    "area": "Bandra",
    "address": "K C Marg, Mount Mary, Bandra West, Mumbai, Maharashtra 400050",
    "lat": 19.0478974,
    "lng": 72.8271497,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Jolly%20Boys%20Sarvajanik%20Ganesh%20Mandal%20Bandra%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0028",
    "rank": 26,
    "name": "Dongricha Raja",
    "area": "Chinch Bunder, Dongri",
    "address": "Chinch Bunder, Dr Meisheri Road, Dongri, Mumbai, Maharashtra 400009",
    "lat": 18.9591904,
    "lng": 72.8385064,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Dongricha%20Raja%20Chinch%20Bunder%20Dongri%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0029",
    "rank": 27,
    "name": "Bhaveshwar Cha Raja",
    "area": "Ghatkopar",
    "address": "Mahatma Gandhi Road, Ghatkopar, Mumbai, Maharashtra 400077",
    "lat": 19.0830513,
    "lng": 72.9049677,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Bhaveshwar%20Cha%20Raja%20Ghatkopar%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0030",
    "rank": 28,
    "name": "Juhu Ganesh Mandal",
    "area": "Juhu",
    "address": "Juhu, Mumbai, Maharashtra",
    "lat": 19.1070215,
    "lng": 72.8275275,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Juhu%20Ganesh%20Mandal%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0031",
    "rank": 29,
    "name": "Akhil Chandanwadi Cha Raja",
    "area": "Chandanwadi",
    "address": "Chandanwadi, near Marine Lines, Mumbai, Maharashtra 400002",
    "lat": 18.945764,
    "lng": 72.8237193,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Akhil%20Chandanwadi%20Cha%20Raja%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0032",
    "rank": 30,
    "name": "Kolbhat Lane Cha Raja",
    "area": "Kolbhat Lane",
    "address": "Kolbhat Lane, Chira Bazaar, Kalbadevi, Mumbai, Maharashtra 400002",
    "lat": 18.9492575,
    "lng": 72.8279382,
    "status": "unverified",
    "confidence": "approximate",
    "pinPrecision": "Area-level estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Area-level estimate. Confirm exact venue before publishing.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Kolbhat%20Lane%20Cha%20Raja%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0033",
    "rank": 31,
    "name": "Matoshreecha Vighnaharta",
    "area": "Parel",
    "address": "Matoshree Shivgarjana Mandal, Parel, Mumbai",
    "lat": 19.003,
    "lng": 72.8405,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Neighbourhood estimate",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "Official 2026 source confirms the mandal. Check the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Matoshreecha%20Vighnaharta%20Parel%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0034",
    "rank": 32,
    "name": "Colabyacha Ladka",
    "area": "Colaba",
    "address": "Colaba, Mumbai",
    "lat": 18.9067,
    "lng": 72.8147,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Area-centre placeholder",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; the area-level pin needs an entrance check.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Colabyacha%20Ladka%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0035",
    "rank": 33,
    "name": "Dharavicha Sukhkarta",
    "area": "Dharavi",
    "address": "Dharavi, Mumbai",
    "lat": 19.0445,
    "lng": 72.8553,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Area-centre placeholder",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; the area-level pin needs an entrance check.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Dharavicha%20Sukhkarta%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0036",
    "rank": 34,
    "name": "Ekveera Mitra Mandal",
    "area": "Kurla West",
    "address": "Halav Pool Hall Road, Mahajan Wadi, Kurla West, Mumbai 400070",
    "lat": 19.077411,
    "lng": 72.882986,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; this pin uses BMC 2023 point geometry.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.077411%2C72.882986",
    "source": "official"
  },
  {
    "id": "P0037",
    "rank": 35,
    "name": "Malad Cha Maharaja",
    "area": "Malad",
    "address": "Malad, Mumbai",
    "lat": 19.186,
    "lng": 72.848,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Area-centre placeholder",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; the area-level pin needs an entrance check.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Malad%20Cha%20Maharaja%2C%20Malad",
    "source": "official"
  },
  {
    "id": "P0038",
    "rank": 36,
    "name": "Site Group",
    "area": "Malad West",
    "address": "1 S.V. Road, Bhadran Nagar, opposite Sapna Hotel, Malad West, Mumbai 400064",
    "lat": 19.1814,
    "lng": 72.84692,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; this pin uses BMC 2023 point geometry.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.1814%2C72.84692",
    "source": "official"
  },
  {
    "id": "P0039",
    "rank": 37,
    "name": "Mazgaoncha Morya",
    "area": "Mazgaon",
    "address": "Mazgaon, Mumbai",
    "lat": 18.9717,
    "lng": 72.844,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Area-centre placeholder",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; the area-level pin needs an entrance check.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Mazgaoncha%20Morya%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0040",
    "rank": 38,
    "name": "Mumbadevicha Ganraj",
    "area": "Mumbadevi",
    "address": "Mumbadevi, Mumbai",
    "lat": 18.9518,
    "lng": 72.8305,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Area-centre placeholder",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; the area-level pin needs an entrance check.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Mumbadevicha%20Ganraj%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0041",
    "rank": 39,
    "name": "Sioncha Icchapurti",
    "area": "Sion",
    "address": "Sion, Mumbai",
    "lat": 19.0434,
    "lng": 72.8616,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Area-centre placeholder",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; the area-level pin needs an entrance check.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Sioncha%20Icchapurti%20Mumbai",
    "source": "official"
  },
  {
    "id": "P0042",
    "rank": 40,
    "name": "Vashi Cha Raja",
    "area": "Vashi, Navi Mumbai",
    "address": "Vashi, Navi Mumbai",
    "lat": 19.0771,
    "lng": 72.9986,
    "status": "editor_verified",
    "confidence": "approximate",
    "pinPrecision": "Area-centre placeholder",
    "evidenceYear": 2026,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "2026 activity is confirmed; the area-level pin needs an entrance check.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=Vashi%20Cha%20Raja%2C%20Vashi",
    "source": "official"
  },
  {
    "id": "P0043",
    "rank": 41,
    "name": "Akhil Mahakali Sarvajanik Ganeshotsav Mandal",
    "area": "Andheri East",
    "address": "Mahakali Caves Road, Sanskar Seva Mandal, Andheri East, Mumbai 400093",
    "lat": 19.12269,
    "lng": 72.86381,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.12269,72.86381",
    "source": "official"
  },
  {
    "id": "P0044",
    "rank": 42,
    "name": "Guru Kripa Seva Mandal",
    "area": "Bandra West",
    "address": "Raja Ram Wadi, near Dhobi Ghat, Waroda Road, Bandra West, Mumbai 400050",
    "lat": 19.054144,
    "lng": 72.828334,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.054144,72.828334",
    "source": "official"
  },
  {
    "id": "P0045",
    "rank": 43,
    "name": "Jagruti Mitra Mandal",
    "area": "Bhandup West",
    "address": "Motibai Wadi, Station Road, Bhandup West, Mumbai 400078",
    "lat": 19.14426,
    "lng": 72.937826,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.14426,72.937826",
    "source": "official"
  },
  {
    "id": "P0046",
    "rank": 44,
    "name": "Hari Mitra Mandal",
    "area": "Borivali East",
    "address": "Chiku Market, Carter Road No. 6, Borivali East, Mumbai 400066",
    "lat": 19.232278,
    "lng": 72.866076,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.232278,72.866076",
    "source": "official"
  },
  {
    "id": "P0047",
    "rank": 45,
    "name": "Chembur Sarvajanik Shree Ganeshotsav Mandal",
    "area": "Chembur",
    "address": "D-105 Sudha Niwas, V.N. Purav Nagar, Gaothan, Chembur, Mumbai 400071",
    "lat": 19.058952,
    "lng": 72.896731,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.058952,72.896731",
    "source": "official"
  },
  {
    "id": "P0048",
    "rank": 46,
    "name": "Avighna Mitra Mandal",
    "area": "Cuffe Parade, Colaba",
    "address": "Opposite EME Workshop, Captain Prakash Pethe Marg, New Dhobi Ghat, Cuffe Parade, Mumbai 400005",
    "lat": 18.917949,
    "lng": 72.824829,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.917949,72.824829",
    "source": "official"
  },
  {
    "id": "P0049",
    "rank": 47,
    "name": "Bhatia Bhuvan Ganeshotsav Mandal",
    "area": "Dadar West",
    "address": "A/69 Bhatia Bhuvan, D.S. Babrekar Marg, Gokhale Road, Dadar, Mumbai 400028",
    "lat": 19.009276,
    "lng": 72.830693,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.009276,72.830693",
    "source": "official"
  },
  {
    "id": "P0050",
    "rank": 48,
    "name": "Dahisar Bhaji Market Bal Mitra Mandal",
    "area": "Dahisar East",
    "address": "Bhaji Market Road, Y.T. Road, Dahisar East, Mumbai 400068",
    "lat": 19.248326,
    "lng": 72.860468,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.248326,72.860468",
    "source": "official"
  },
  {
    "id": "P0051",
    "rank": 49,
    "name": "Janseva Krutishil Mandal",
    "area": "Dharavi",
    "address": "412, 90 Feet Road, Joglekar Nala, Shivshankar Nagar, Dharavi, Mumbai 400017",
    "lat": 19.047627,
    "lng": 72.86068,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.047627,72.86068",
    "source": "official"
  },
  {
    "id": "P0052",
    "rank": 50,
    "name": "Karwar Street Mitra Mandal",
    "area": "Fort",
    "address": "31/33 S.B.S. Road, Vaju Kotak Marg, Fort, Mumbai 400001",
    "lat": 18.937073,
    "lng": 72.838179,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.937073,72.838179",
    "source": "official"
  },
  {
    "id": "P0053",
    "rank": 51,
    "name": "Jugnu Sports Club",
    "area": "Ghatkopar East",
    "address": "3 Hingwala Cross Lane, Babli Konekar Marg, Ghatkopar East, Mumbai 400077",
    "lat": 19.083475,
    "lng": 72.90995,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.083475,72.90995",
    "source": "official"
  },
  {
    "id": "P0054",
    "rank": 52,
    "name": "Paper Mill Lane V.P. Road S.G.M.",
    "area": "Girgaon",
    "address": "Paper Mill Lane, V.P. Road, Noor Mohammad Building, Girgaon, Mumbai 400004",
    "lat": 18.957775,
    "lng": 72.819015,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.957775,72.819015",
    "source": "official"
  },
  {
    "id": "P0055",
    "rank": 53,
    "name": "Khadicha Raja Guruchandramani Sarvajanik Mandal",
    "area": "Goregaon West",
    "address": "Behind Pumping House, Link Road, Indira Nagar, Goregaon West, Mumbai 400104",
    "lat": 19.161269,
    "lng": 72.834743,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.161269,72.834743",
    "source": "official"
  },
  {
    "id": "P0056",
    "rank": 54,
    "name": "Morya SRA CHS",
    "area": "Govandi",
    "address": "Govandi Station Road, Ganeshwadi, Deonar, behind Lakme Company, Mumbai 400088",
    "lat": 19.053405,
    "lng": 72.914609,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.053405,72.914609",
    "source": "official"
  },
  {
    "id": "P0057",
    "rank": 55,
    "name": "Grant Road Bal Mitra Mandal",
    "area": "Grant Road",
    "address": "Alibhai Premji Marg, opposite Phiroza Mansion, near Grant Road Station, Mumbai 400007",
    "lat": 18.964199,
    "lng": 72.819139,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.964199,72.819139",
    "source": "official"
  },
  {
    "id": "P0058",
    "rank": 56,
    "name": "Navchaitanya Mandal",
    "area": "Jogeshwari East",
    "address": "KEM Ganesh Katta, Ganesh Maidan, Shahid Road, Shivaji Nagar, Jogeshwari East, Mumbai 400060",
    "lat": 19.132124,
    "lng": 72.857418,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.132124,72.857418",
    "source": "official"
  },
  {
    "id": "P0059",
    "rank": 57,
    "name": "Shiv Samarth Mitra Mandal",
    "area": "Juhu",
    "address": "5/92 Tushar Bindu, Gulmohar Cross Road No. 7, Juhu Scheme, Mumbai 400049",
    "lat": 19.113899,
    "lng": 72.835656,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.113899,72.835656",
    "source": "official"
  },
  {
    "id": "P0060",
    "rank": 58,
    "name": "Omkar Tarun Mitra Mandal",
    "area": "Kalachowki",
    "address": "G.D. Ambekar Road, near Milan Industries, Parshuram Nagar, Kalachowki, Mumbai 400033",
    "lat": 18.991659,
    "lng": 72.841578,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.991659,72.841578",
    "source": "official"
  },
  {
    "id": "P0061",
    "rank": 59,
    "name": "Ganesh Seva Sangh",
    "area": "Kandivali West",
    "address": "Near Suman Building, Shankar Lane, Kajupada, Kandivali West, Mumbai 400067",
    "lat": 19.19808,
    "lng": 72.843341,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.19808,72.843341",
    "source": "official"
  },
  {
    "id": "P0062",
    "rank": 60,
    "name": "Navtarun Krida Mandal",
    "area": "Khar East",
    "address": "Indira Nagar, Prabhat Vyayam Shala Marg, Khar East, Mumbai 400055",
    "lat": 19.073569,
    "lng": 72.846234,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.073569,72.846234",
    "source": "official"
  },
  {
    "id": "P0063",
    "rank": 61,
    "name": "1st Parsiwada Sarvajanik Utsav Mandal",
    "area": "Khetwadi",
    "address": "Hira Building, 1st Parsiwada Lane, Nanubhai Desai Road, Khetwadi, Mumbai 400004",
    "lat": 18.956285,
    "lng": 72.826254,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.956285,72.826254",
    "source": "official"
  },
  {
    "id": "P0064",
    "rank": 62,
    "name": "Hiramani Super Market Ganeshotsav Mandal",
    "area": "Lalbaug",
    "address": "Riddhi Siddhi Society, Dr Babasaheb Ambedkar Road, Lalbaug, Mumbai 400012",
    "lat": 18.99523,
    "lng": 72.836604,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.99523,72.836604",
    "source": "official"
  },
  {
    "id": "P0065",
    "rank": 63,
    "name": "Liberty Garden Sarvajanik Shree Ganeshutsav Mandal",
    "area": "Malad West",
    "address": "Veer Savarkar Chowk, Liberty Garden, near Adani Billing Office, Malad West, Mumbai 400064",
    "lat": 19.187441,
    "lng": 72.842065,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.187441,72.842065",
    "source": "official"
  },
  {
    "id": "P0066",
    "rank": 64,
    "name": "Royal Cricket Club",
    "area": "Matunga",
    "address": "Near A/42 and St Paul Church, Dr Ambedkar Road, Matunga Labour Camp, Mumbai 400019",
    "lat": 19.026539,
    "lng": 72.854957,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.026539,72.854957",
    "source": "official"
  },
  {
    "id": "P0067",
    "rank": 65,
    "name": "Shambhucha Maharaja",
    "area": "Mulund West",
    "address": "Jivraj Bhanji Hall, Indira Nagar No. 3, Mulund West, Mumbai 400080",
    "lat": 19.16617,
    "lng": 72.94999,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.16617,72.94999",
    "source": "official"
  },
  {
    "id": "P0068",
    "rank": 66,
    "name": "Vidhyarthi Seva Mandal",
    "area": "Parel",
    "address": "Dharati CHS, Dr Ambedkar Road, G.M. Nangre Marg, Parel, Mumbai 400012",
    "lat": 18.999395,
    "lng": 72.837693,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=18.999395,72.837693",
    "source": "official"
  },
  {
    "id": "P0069",
    "rank": 67,
    "name": "Bal Mitra Mandal (Kalinacha Vighnaharta)",
    "area": "Kalina, Santacruz East",
    "address": "Mahatma Phule Nagar, behind Kalina Church, Kalina, Santacruz East, Mumbai 400029",
    "lat": 19.078816,
    "lng": 72.867045,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.078816,72.867045",
    "source": "official"
  },
  {
    "id": "P0070",
    "rank": 68,
    "name": "Savali Seva Foundation",
    "area": "Vikhroli East",
    "address": "173/2728/8A, near Samaj Mandir Hall, Tagore Nagar, Vikhroli East, Mumbai 400083",
    "lat": 19.124907,
    "lng": 72.932748,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.124907,72.932748",
    "source": "official"
  },
  {
    "id": "P0071",
    "rank": 69,
    "name": "Ramnagar Utsav Mandal",
    "area": "Wadala West",
    "address": "Room 2, Ram Nagar CHS Building 1, B.K. Marg, Wadala West, Mumbai 400031",
    "lat": 19.01578,
    "lng": 72.85249,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.01578,72.85249",
    "source": "official"
  },
  {
    "id": "P0072",
    "rank": 70,
    "name": "Shivsfurti Mandal",
    "area": "Worli",
    "address": "Siddharth Nagar, Dr Annie Besant Road, Worli Naka, Mumbai 400018",
    "lat": 19.000234,
    "lng": 72.816547,
    "status": "carried_over",
    "confidence": "approximate",
    "pinPrecision": "BMC point geometry (2023)",
    "evidenceYear": 2023,
    "aarti_times": "Aarti time not published",
    "timingDetails": "Exact aarti timings have not been verified. Check the mandal's official Instagram or Facebook closer to the date.",
    "sourceLine": "BMC 2023 mandap record. Confirm 2026 activity and the exact entrance before visiting.",
    "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=19.000234,72.816547",
    "source": "official"
  }
];

window.MODAK_STOPS_DATA = [
  {
    "name": "Aaswad",
    "area": "Dadar West",
    "address": "4, Sanskruti Building, Gadkari Chowk, Lady Jamshedji Road, Dadar West, Mumbai 400028",
    "notableFor": "Steamed ukadiche modak and seasonal modak varieties",
    "lat": 19.0250391,
    "lng": 72.8405675,
    "type": "shop"
  },
  {
    "name": "Panshikar Mithai Kendra",
    "area": "Girgaon",
    "address": "162, Mohan Building, Jagannath Shankarseth Road, Girgaon, Mumbai 400004",
    "notableFor": "Traditional Maharashtrian mithai and festive modak",
    "lat": 18.9536335,
    "lng": 72.8196898,
    "type": "shop"
  },
  {
    "name": "Modakam",
    "area": "Prabhadevi",
    "address": "Shop 8, Kamana CHS, S K Bole Road, Prabhadevi, Mumbai 400028",
    "notableFor": "Fresh steamed ukadiche modak near Siddhivinayak",
    "lat": 19.0168775,
    "lng": 72.8304004,
    "type": "shop"
  },
  {
    "name": "Ketkar Caterers",
    "area": "Dadar East",
    "address": "Harganga Mahal Annexe, Sir Bhalchandra Road, Dadar East, Mumbai 400014",
    "notableFor": "Bulk festive modak orders and Maharashtrian catering",
    "lat": 19.0196045,
    "lng": 72.847756,
    "type": "shop"
  },
  {
    "name": "Eastern House by Sangeeta",
    "area": "Fort",
    "address": "47/49, Mehta Building, Nagindas Master Road, Kala Ghoda, Fort, Mumbai 400001",
    "notableFor": "Eastern Malai Peda and festive sweets",
    "lat": 18.9294333,
    "lng": 72.8323238,
    "type": "shop"
  },
  {
    "name": "Sangeeta Sweets",
    "area": "Cumballa Hill",
    "address": "Vellard View, 26 Dr Gopalrao Deshmukh Marg, Cumballa Hill, Mumbai 400026",
    "notableFor": "Classic mithai and Ganesh festival modak",
    "lat": 18.9720742,
    "lng": 72.8092001,
    "type": "shop"
  },
  {
    "name": "New Karachi Sweets",
    "area": "Khar West",
    "address": "Shop 6, Ajanta Building, 3rd Road, Khar West, Mumbai 400052",
    "notableFor": "Traditional ghee and chocolate modak",
    "lat": 19.0682411,
    "lng": 72.8400412,
    "type": "shop"
  },
  {
    "name": "Bombay Sweet Shop",
    "area": "Byculla East",
    "address": "Unit 1, JAK Compound, Dadoji Konddeo Cross Lane, Byculla East, Mumbai 400027",
    "notableFor": "Modern Indian mithai and festive modak boxes",
    "lat": 18.9813037,
    "lng": 72.8390818,
    "type": "shop"
  },
  {
    "name": "Panchali Mumbai Caterers",
    "area": "Vile Parle East",
    "address": "Shop 13, Plot 7, Thosar Wadi, Hanuman Cross Road, Vile Parle East, Mumbai 400057",
    "notableFor": "Maharashtrian sweets and festive catering",
    "lat": 19.1046699,
    "lng": 72.8509443,
    "type": "shop"
  },
  {
    "name": "Chandu Halwai",
    "area": "Lower Parel",
    "address": "5, 148A Hargun House, Annie Besant Road, Lower Parel, Mumbai 400018",
    "notableFor": "Mawa sweets and festive modak",
    "lat": 19.0126169,
    "lng": 72.8226645,
    "type": "shop"
  }
];
