/**
 * Aamche Bappa - Regional Ganpati Coverage for Maharashtra, Karnataka & Goa
 * Fully evaluated dataset with detailed pandal information, timings, and modak stops.
 */

window.REGIONAL_PANDALS_DATA = [
  // ==========================================
  // MAHARASHTRA (Outside Mumbai)
  // ==========================================
  // Pune — Manache 5 Ganpatis & Historical Mandals
  {
    id: "MH-PUN-001",
    rank: 71,
    name: "Shree Kasba Ganpati (Manacha 1st)",
    area: "Kasba Peth",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "159, Kasba Peth, Pune 411011",
    lat: 18.5196,
    lng: 73.8567,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Historic Temple Landmark",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 12 PM | 8 PM",
    timingDetails: "Gramdaivat of Pune, established by Chhatrapati Shivaji Maharaj and Rajmata Jijabai in 1639. Holds the 1st right of immersion.",
    sourceLine: "Official Kasba Ganpati Mandal 2026 schedule verified.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Kasba+Ganpati+Pune",
    source: "official"
  },
  {
    id: "MH-PUN-002",
    rank: 72,
    name: "Tambdi Jogeshwari Ganpati (Manacha 2nd)",
    area: "Budhwar Peth",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "33A, Budhwar Peth, Pune 411002",
    lat: 18.5174,
    lng: 73.8562,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 7:30 PM",
    timingDetails: "Second Manacha Ganpati in Pune, patronized by Peshwas and located at the historic Jogeshwari Devi temple premises.",
    sourceLine: "Tambdi Jogeshwari Sarvajanik Ganeshotsav Mandal 2026 verified.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Tambdi+Jogeshwari+Ganpati+Pune",
    source: "official"
  },
  {
    id: "MH-PUN-003",
    rank: 73,
    name: "Guruji Talim Ganpati (Manacha 3rd)",
    area: "Ganpati Chowk, Laxmi Road",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "Laxmi Road, Budhwar Peth, Pune 411002",
    lat: 18.5158,
    lng: 73.8561,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 9 AM | 8 PM",
    timingDetails: "Third Manacha Ganpati, established in 1887 by Hindu and Muslim wrestling ustads symbolising communal brotherhood.",
    sourceLine: "Guruji Talim Trust 2026 public confirmation.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Guruji+Talim+Ganpati+Pune",
    source: "official"
  },
  {
    id: "MH-PUN-004",
    rank: 74,
    name: "Tulshibaug Ganpati (Manacha 4th)",
    area: "Tulshibaug",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "Tulshibaug, Budhwar Peth, Pune 411002",
    lat: 18.5139,
    lng: 73.8555,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 12:30 PM | 8:30 PM",
    timingDetails: "Fourth Manacha Ganpati, renowned for its majestic 14-foot glass-fiber and clay idol adorned with handcrafted silver ornaments.",
    sourceLine: "Tulshibaug Sarvajanik Ganeshotsav Mandal 2026 confirmation.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Tulshibaug+Ganpati+Pune",
    source: "official"
  },
  {
    id: "MH-PUN-005",
    rank: 75,
    name: "Kesari Wada Ganpati (Manacha 5th)",
    area: "Narayan Peth",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "Kesari Wada, 568, Narayan Peth, Pune 411030",
    lat: 18.5238,
    lng: 73.8496,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Historic Courtyard",
    evidenceYear: 2026,
    aarti_times: "Aarti: 7:30 AM | 7:30 PM",
    timingDetails: "Fifth Manacha Ganpati, started by Lokmanya Bal Gangadhar Tilak in 1893 at Kesari Wada as the cradle of public Ganeshotsav.",
    sourceLine: "Kesari Mahratta Trust 2026 public schedule.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Kesari+Wada+Ganpati+Pune",
    source: "official"
  },
  {
    id: "MH-PUN-006",
    rank: 76,
    name: "Shreemant Dagdusheth Halwai Ganpati",
    area: "Budhwar Peth / Shivaji Road",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "Ganpati Bhavan, 250, Budhwar Peth, Shivaji Road, Pune 411002",
    lat: 18.5164,
    lng: 73.8565,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 7:30 AM | 12 PM | 7:30 PM | 10:30 PM",
    timingDetails: "World-famous Pune landmark. Visited by millions during the festival, famous for spectacular illuminated temple replicas and gold-clad idol.",
    sourceLine: "Shreemant Dagdusheth Halwai Public Ganpati Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Dagdusheth+Halwai+Ganpati+Pune",
    source: "official"
  },
  {
    id: "MH-PUN-007",
    rank: 77,
    name: "Akhil Mandai Mandal (Sharada Gajanan)",
    area: "Mandai, Shukrawar Peth",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "Mahatma Phule Mandai, Shukrawar Peth, Pune 411002",
    lat: 18.5133,
    lng: 73.8566,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "Iconic idol seated with Goddess Sharada on a swing, celebrated for over a century by Pune's market traders and community.",
    sourceLine: "Akhil Mandai Ganpati Mandal 2026 verified.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Akhil+Mandai+Mandal+Pune",
    source: "official"
  },
  {
    id: "MH-PUN-008",
    rank: 78,
    name: "Hutatma Babu Genu Mandal",
    area: "Budhwar Peth",
    city: "Pune",
    state: "Maharashtra",
    region: "Pune",
    address: "Budhwar Peth, near Tulshibaug, Pune 411002",
    lat: 18.5160,
    lng: 73.8559,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8 PM",
    timingDetails: "Named in honor of national freedom fighter Babu Genu; famous for its magnificent golden chariot and floral decor.",
    sourceLine: "Hutatma Babu Genu Mandal Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Hutatma+Babu+Genu+Ganpati+Pune",
    source: "official"
  },

  // Maharashtra — Ashtavinayak Sacred Pilgrimage
  {
    id: "MH-ASH-001",
    rank: 79,
    name: "Mayureshwar Ganpati Temple (Ashtavinayak)",
    area: "Morgaon",
    city: "Morgaon",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Morgaon, Baramati Taluka, Pune District 412304",
    lat: 18.2755,
    lng: 74.3175,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 5 AM | 12 PM | 8 PM | 10 PM",
    timingDetails: "First and most prominent of the Ashtavinayak pilgrimage temples. Located on the banks of Karha river.",
    sourceLine: "Chinchwad Devasthan Trust 2026 official schedule.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mayureshwar+Temple+Morgaon",
    source: "official"
  },
  {
    id: "MH-ASH-002",
    rank: 80,
    name: "Siddhivinayak Temple, Siddhatek (Ashtavinayak)",
    area: "Siddhatek",
    city: "Siddhatek",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Siddhatek, Karjat Taluka, Ahmednagar District 414403",
    lat: 18.3562,
    lng: 74.8213,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 5:30 AM | 12:30 PM | 7:30 PM",
    timingDetails: "Second Ashtavinayak temple, seated on a hillock overlooking the Bhima river. Only Ashtavinayak with trunk turned right.",
    sourceLine: "Siddhatek Devasthan Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Siddhivinayak+Temple+Siddhatek",
    source: "official"
  },
  {
    id: "MH-ASH-003",
    rank: 81,
    name: "Ballaleshwar Temple, Pali (Ashtavinayak)",
    area: "Pali",
    city: "Pali",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Pali, Sudhagad Taluka, Raigad District 410205",
    lat: 18.5367,
    lng: 73.2215,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 5 AM | 12 PM | 7 PM | 10 PM",
    timingDetails: "Third Ashtavinayak temple, surrounded by the Sarasgad fort and Amba river. Only Ganpati temple named after his ardent boy devotee Ballal.",
    sourceLine: "Ballaleshwar Devasthan Trust Pali 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ballaleshwar+Temple+Pali",
    source: "official"
  },
  {
    id: "MH-ASH-004",
    rank: 82,
    name: "Varadvinayak Temple, Mahad (Ashtavinayak)",
    area: "Mahad, Khalapur",
    city: "Mahad",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Mahad Village, Khalapur, Raigad District 410203",
    lat: 18.8258,
    lng: 73.3155,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 6 AM | 12 PM | 8 PM",
    timingDetails: "Fourth Ashtavinayak shrine. An eternal flame (Nandadweep) has burned continuously in the sanctum since 1892.",
    sourceLine: "Varadvinayak Devasthan Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Varadvinayak+Temple+Mahad",
    source: "official"
  },
  {
    id: "MH-ASH-005",
    rank: 83,
    name: "Chintamani Temple, Theur (Ashtavinayak)",
    area: "Theur",
    city: "Theur",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Theur, Haveli Taluka, Pune District 412110",
    lat: 18.5284,
    lng: 74.0537,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 5 AM | 12:30 PM | 8 PM",
    timingDetails: "Fifth Ashtavinayak shrine, at the sacred confluence of Mula-Mutha rivers. Beloved retreat of Peshwa Madhavrao I.",
    sourceLine: "Chintamani Devasthan Trust Theur 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Chintamani+Temple+Theur",
    source: "official"
  },
  {
    id: "MH-ASH-006",
    rank: 84,
    name: "Girijatmaj Temple, Lenyadri (Ashtavinayak)",
    area: "Lenyadri Caves",
    city: "Junnar",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Lenyadri, Junnar Taluka, Pune District 410502",
    lat: 19.2407,
    lng: 73.8864,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Rock-cut Cave 7",
    evidenceYear: 2026,
    aarti_times: "Aarti: 6 AM | 12 PM | 6:30 PM",
    timingDetails: "Sixth Ashtavinayak shrine. Only temple carved directly into the rock face of an ancient Buddhist cave complex (Cave 7, 283 stone steps).",
    sourceLine: "Lenyadri Ganpati Devasthan 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Lenyadri+Ganpati+Junnar",
    source: "official"
  },
  {
    id: "MH-ASH-007",
    rank: 85,
    name: "Vighnahar Temple, Ozar (Ashtavinayak)",
    area: "Ozar",
    city: "Ozar",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Ozar, Junnar Taluka, Pune District 410504",
    lat: 19.1912,
    lng: 73.9587,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 5:30 AM | 12 PM | 7:30 PM",
    timingDetails: "Seventh Ashtavinayak shrine on the banks of Kukadi river, celebrated for its golden dome, diamond eyes, and ruby on the navel.",
    sourceLine: "Vighnahar Devasthan Trust Ozar 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Vighnahar+Temple+Ozar",
    source: "official"
  },
  {
    id: "MH-ASH-008",
    rank: 86,
    name: "Mahaganapati Temple, Ranjangaon (Ashtavinayak)",
    area: "Ranjangaon",
    city: "Ranjangaon",
    state: "Maharashtra",
    region: "Ashtavinayak",
    address: "Ranjangaon, Shirur Taluka, Pune District 412209",
    lat: 18.7561,
    lng: 74.2435,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 5:30 AM | 12 PM | 7:30 PM | 10 PM",
    timingDetails: "Eighth Ashtavinayak shrine. Depicts the fierce Mahaganapati with 10 trunks and 20 arms worshipped by Lord Shiva before defeating Tripurasura.",
    sourceLine: "Mahaganapati Devasthan Trust Ranjangaon 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mahaganapati+Temple+Ranjangaon",
    source: "official"
  },

  // Maharashtra — Konkan, Coastal & Regional Landmarks
  {
    id: "MH-KON-001",
    rank: 87,
    name: "Swayambhu Ganpatipule Temple",
    area: "Ganpatipule Beach",
    city: "Ratnagiri",
    state: "Maharashtra",
    region: "Konkan",
    address: "Ganpatipule, Ratnagiri District 415615",
    lat: 17.1458,
    lng: 73.2678,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Beachside Sanctuary",
    evidenceYear: 2026,
    aarti_times: "Aarti: 5 AM | 12 PM | 7 PM",
    timingDetails: "400-year-old self-manifested monolith Ganesha on white sands facing the Arabian Sea. The entire hill is circumambulated by devotees.",
    sourceLine: "Ganpatipule Sansthan 2026 official calendar.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ganpatipule+Temple+Ratnagiri",
    source: "official"
  },
  {
    id: "MH-KON-002",
    rank: 88,
    name: "Suvarna Ganesh Temple, Diveagar",
    area: "Diveagar Beach",
    city: "Shrivardhan",
    state: "Maharashtra",
    region: "Konkan",
    address: "Diveagar, Shrivardhan Taluka, Raigad District 402404",
    lat: 18.1706,
    lng: 72.9972,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Famed Konkan coastal pilgrimage sanctuary revered for its miraculous golden idol discovered in a coconut orchard in 1997.",
    sourceLine: "Suvarna Ganesh Mandir Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Suvarna+Ganesh+Temple+Diveagar",
    source: "official"
  },
  {
    id: "MH-KON-003",
    rank: 89,
    name: "Dashabhuja Ganpati Temple, Hedvi",
    area: "Hedvi",
    city: "Guhagar",
    state: "Maharashtra",
    region: "Konkan",
    address: "Hedvi Village, Guhagar Taluka, Ratnagiri District 415728",
    lat: 17.3372,
    lng: 73.1895,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Peshwa Era Sanctum",
    evidenceYear: 2026,
    aarti_times: "Aarti: 7:30 AM | 7 PM",
    timingDetails: "Rare white marble idol with 10 arms, carved during the Peshwa regime, situated atop a hill in the scenic coastal village of Hedvi.",
    sourceLine: "Hedvi Devasthan Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Dashabhuja+Ganpati+Hedvi",
    source: "official"
  },
  {
    id: "MH-NAG-001",
    rank: 90,
    name: "Shree Tekdi Ganpati Temple, Nagpur",
    area: "Sitabuldi",
    city: "Nagpur",
    state: "Maharashtra",
    region: "Vidarbha",
    address: "Station Road, Sitabuldi, Nagpur 440001",
    lat: 21.1492,
    lng: 79.0827,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Historic Hilltop Shrin",
    evidenceYear: 2026,
    aarti_times: "Aarti: 6 AM | 12 PM | 7:30 PM",
    timingDetails: "Over 250-year-old self-manifested shrine atop Tekdi hill, revered as the patron deity of Vidarbha and Nagpur.",
    sourceLine: "Tekdi Ganesh Mandir Trust 2026 verified.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Tekdi+Ganpati+Nagpur",
    source: "official"
  },
  {
    id: "MH-NSK-001",
    rank: 91,
    name: "Navshya Ganpati Temple, Nashik",
    area: "Anandvalli",
    city: "Nashik",
    state: "Maharashtra",
    region: "North Maharashtra",
    address: "Gangapur Road, Anandvalli, Nashik 422013",
    lat: 20.0163,
    lng: 73.7432,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Riverfront Temple",
    evidenceYear: 2026,
    aarti_times: "Aarti: 7 AM | 12:30 PM | 7:30 PM",
    timingDetails: "300-year-old historic Peshwa temple on the banks of Godavari river, renowned for granting the vows (navas) of devotees.",
    sourceLine: "Navshya Ganpati Trust 2026 verified.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Navshya+Ganpati+Nashik",
    source: "official"
  },
  {
    id: "MH-KLP-001",
    rank: 92,
    name: "Shahupuri Sarvajanik Ganeshotsav, Kolhapur",
    area: "Shahupuri",
    city: "Kolhapur",
    state: "Maharashtra",
    region: "Western Maharashtra",
    address: "Shahupuri 2nd Lane, Kolhapur 416001",
    lat: 16.7022,
    lng: 74.2405,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "Kolhapur's pride, celebrated for traditional eco-friendly Shadu clay murtis and rhythmic Kolhapuri Dhol-Tasha-Pathak immersion processions.",
    sourceLine: "Shahupuri Ganeshotsav Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Shahupuri+Ganpati+Kolhapur",
    source: "official"
  },

  // ==========================================
  // GOA
  // ==========================================
  // Panaji & Tiswadi
  {
    id: "GA-PAN-001",
    rank: 93,
    name: "Goa Reserve Police (GRP) Ganeshotsav",
    area: "Altinho",
    city: "Panaji",
    state: "Goa",
    region: "Panaji & North Goa",
    address: "Police Grounds, Altinho, Panaji, Goa 403001",
    lat: 15.4923,
    lng: 73.8205,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Police Headquarters",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Goa's premier state-service celebration perched on Altinho hill, attracting thousands for cultural theatricals and evening aartis.",
    sourceLine: "Goa Reserve Police Welfare Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Altinho+GRP+Ganeshotsav+Panaji",
    source: "official"
  },
  {
    id: "GA-PAN-002",
    rank: 94,
    name: "Panaji Municipal Market Sarvajanik Ganeshotsav",
    area: "Municipal Market",
    city: "Panaji",
    state: "Goa",
    region: "Panaji & North Goa",
    address: "Panaji Market Complex, Dr Pissurlenkar Road, Panaji, Goa 403001",
    lat: 15.4989,
    lng: 73.8278,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Commercial Hub",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8 PM",
    timingDetails: "The oldest and most vibrant public celebration in the Goan capital, organized with deep devotion by the city's trade community.",
    sourceLine: "Panaji Market Vyapari Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Panaji+Market+Ganeshotsav+Goa",
    source: "official"
  },
  {
    id: "GA-PAN-003",
    rank: 95,
    name: "Mala Sarvajanik Ganeshotsav Mandal",
    area: "Mala / Fontainhas",
    city: "Panaji",
    state: "Goa",
    region: "Panaji & North Goa",
    address: "Near Mala Bridge, Fontainhas, Panaji, Goa 403001",
    lat: 15.4935,
    lng: 73.8310,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Neighborhood Square",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Traditional community festival nestled beside the heritage Latin Quarter of Fontainhas, celebrated with classical Konkani bhajan nights.",
    sourceLine: "Mala Ganeshotsav Samiti 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mala+Ganeshotsav+Panaji+Goa",
    source: "official"
  },
  {
    id: "GA-TIS-001",
    rank: 96,
    name: "Brahmeshwar Yuvak Sangh Ganeshotsav",
    area: "St. Estevam Island",
    city: "Tiswadi",
    state: "Goa",
    region: "Panaji & North Goa",
    address: "Akhada, St. Estevam, Tiswadi, Goa 403106",
    lat: 15.5007,
    lng: 73.9688,
    status: "confirmed",
    confidence: "exact",
    pinPrecision: "Island Community Hall",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "Vibrant river-island Ganeshotsav uniting the village of St. Estevam in traditional Goan folk performances and community feast.",
    sourceLine: "Goa Cultural Directorate 2026 registered pandal.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=St+Estevam+Ganeshotsav+Goa",
    source: "official"
  },

  // Goa — Ponda (The Spiritual Temple Heart of Goa)
  {
    id: "GA-PON-001",
    rank: 97,
    name: "Shree Zareshwar Sarvajanik Ganeshotsav Mandal",
    area: "Old Bus Stand / Indira Market",
    city: "Ponda",
    state: "Goa",
    region: "Ponda",
    address: "Old Bus Stand Road, Indira Market, Ponda, Goa 403401",
    lat: 15.4024,
    lng: 74.0081,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Town Center",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8 PM",
    timingDetails: "Ponda's grandest festival gathering, hosting all-Goa inter-school ghode modni and classical singing competitions.",
    sourceLine: "Zareshwar Ganeshotsav Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Zareshwar+Ganpati+Ponda+Goa",
    source: "official"
  },
  {
    id: "GA-PON-002",
    rank: 98,
    name: "Gopal Ganapati Temple, Farmagudi",
    area: "Farmagudi",
    city: "Ponda",
    state: "Goa",
    region: "Ponda",
    address: "Farmagudi Hill, NH4A, Ponda, Goa 403401",
    lat: 15.4192,
    lng: 73.9854,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 7:30 AM | 12:30 PM | 7:30 PM",
    timingDetails: "Historic temple commissioned by Dayanand Bandodkar celebrating Chhatrapati Shivaji Maharaj's spiritual connection to Goa.",
    sourceLine: "Farmagudi Devasthan 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Gopal+Ganapati+Temple+Farmagudi",
    source: "official"
  },
  {
    id: "GA-PON-003",
    rank: 99,
    name: "Shree Mahaganapati Temple, Khandola / Marcel",
    area: "Khandola",
    city: "Marcel",
    state: "Goa",
    region: "Ponda",
    address: "Marcel, Khandola, Ponda Taluka, Goa 403107",
    lat: 15.5186,
    lng: 73.9782,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Ancient Devasthan",
    evidenceYear: 2026,
    aarti_times: "Aarti: 7 AM | 12 PM | 7 PM",
    timingDetails: "Sacred ancestral Ganpati temple consecrated after being rescued from Divar island during the 16th-century Portuguese era.",
    sourceLine: "Mahaganapati Sansthan Khandola 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mahaganapati+Temple+Khandola+Marcel",
    source: "official"
  },
  {
    id: "GA-PON-004",
    rank: 100,
    name: "Shivkrupanand Swami Ganeshotsav",
    area: "Shiroda",
    city: "Ponda",
    state: "Goa",
    region: "Ponda",
    address: "Shiroda Bazaar, Ponda, Goa 403103",
    lat: 15.3323,
    lng: 74.0272,
    status: "confirmed",
    confidence: "exact",
    pinPrecision: "Village Center",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Major spiritual and cultural festival in South Ponda, recognized for philanthropic youth drives and eco-friendly murtis.",
    sourceLine: "Shiroda Sarvajanik Ganeshotsav Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Shiroda+Ganeshotsav+Ponda+Goa",
    source: "official"
  },

  // Goa — Margao & South Goa
  {
    id: "GA-MAR-001",
    rank: 101,
    name: "Margao Municipal Garden Sarvajanik Ganeshotsav",
    area: "Municipal Garden / Pipa",
    city: "Margao",
    state: "Goa",
    region: "Margao & South Goa",
    address: "Aga Khan Park, Municipal Garden, Margao, Goa 403601",
    lat: 15.2736,
    lng: 73.9582,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "City Center Park",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8 PM",
    timingDetails: "The premier public festival in South Goa, drawing huge evening crowds for renowned Konkani dramas (tiatr/natak) and Maha Aarti.",
    sourceLine: "Margao Sarvajanik Ganeshotsav Samiti 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Margao+Municipal+Garden+Ganeshotsav",
    source: "official"
  },
  {
    id: "GA-MAR-002",
    rank: 102,
    name: "Navelim Sarvajanik Shree Ganeshotsav Trust",
    area: "Navelim, Salcete",
    city: "Margao",
    state: "Goa",
    region: "Margao & South Goa",
    address: "Near Navelim Church Ground, Margao, Goa 403707",
    lat: 15.2640,
    lng: 73.9555,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Community Ground",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Beloved neighborhood pandal in Salcete known for interfaith harmony, charity drives, and devotional music recitals.",
    sourceLine: "Navelim Ganeshotsav Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Navelim+Ganeshotsav+Margao+Goa",
    source: "official"
  },
  {
    id: "GA-MAR-003",
    rank: 103,
    name: "Aquem Sarvajanik Ganeshotsav Mandal",
    area: "Aquem Alto",
    city: "Margao",
    state: "Goa",
    region: "Margao & South Goa",
    address: "Aquem Alto, near Damodar Temple, Margao, Goa 403601",
    lat: 15.2812,
    lng: 73.9715,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "Vibrant community mandal in eastern Margao beside the historic Shree Damodar temple.",
    sourceLine: "Aquem Ganeshotsav Samiti 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Aquem+Ganeshotsav+Margao",
    source: "official"
  },
  {
    id: "GA-VAS-001",
    rank: 104,
    name: "Vasco da Gama Sarvajanik Ganeshotsav",
    area: "Swatantra Path",
    city: "Vasco da Gama",
    state: "Goa",
    region: "Margao & South Goa",
    address: "Swatantra Path, Joshi Ground, Vasco da Gama, Goa 403802",
    lat: 15.3982,
    lng: 73.8118,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Port City Center",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "Goa's historic port city celebration, famous for coastal musical programs and festive street illuminations.",
    sourceLine: "Vasco Sarvajanik Ganeshotsav Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Vasco+Sarvajanik+Ganeshotsav+Goa",
    source: "official"
  },
  {
    id: "GA-SAN-001",
    rank: 105,
    name: "Sanguem Police Station Ganeshotsav",
    area: "Sanguem Town",
    city: "Sanguem",
    state: "Goa",
    region: "Margao & South Goa",
    address: "Police Station Premises, Sanguem, Goa 403704",
    lat: 15.2294,
    lng: 74.1518,
    status: "confirmed",
    confidence: "exact",
    pinPrecision: "Civic Ground",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7 PM",
    timingDetails: "Scenic foothills celebration organized by police and local tribal/farming communities in South Goa's hinterlands.",
    sourceLine: "Sanguem Civic Ganeshotsav listing 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Sanguem+Police+Station+Ganeshotsav",
    source: "official"
  },
  {
    id: "GA-SAN-002",
    rank: 106,
    name: "Sarvajanik Ganeshotsav Mandal Tudav",
    area: "Tudav",
    city: "Sanguem",
    state: "Goa",
    region: "Margao & South Goa",
    address: "Tudav, Sanguem Taluka, Goa 403704",
    lat: 15.1960,
    lng: 74.1880,
    status: "confirmed",
    confidence: "approximate",
    pinPrecision: "Village Center",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Traditional community Ganeshotsav in the lush green foothills of the Western Ghats in Sanguem.",
    sourceLine: "Government of Goa Directorate of Art & Culture 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Tudav+Ganeshotsav+Goa",
    source: "official"
  },

  // Goa — Mapusa, Pernem & Bicholim (North Goa)
  {
    id: "GA-MAP-001",
    rank: 107,
    name: "Mapusa Sarvajanik Ganeshotsav Mandal",
    area: "Municipal Market",
    city: "Mapusa",
    state: "Goa",
    region: "Mapusa & North Goa",
    address: "Market Square, Mapusa, Bardez, Goa 403507",
    lat: 15.5925,
    lng: 73.8142,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Market Square",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8 PM",
    timingDetails: "North Goa's biggest market celebration, adorned with traditional handloom drapes and community prasad distribution.",
    sourceLine: "Mapusa Merchant Ganeshotsav Association 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mapusa+Ganeshotsav+Mandal+Goa",
    source: "official"
  },
  {
    id: "GA-BIC-001",
    rank: 108,
    name: "Sarvajanik Ganeshotsav Mandal Bicholim",
    area: "Bicholim Town Center",
    city: "Bicholim",
    state: "Goa",
    region: "Mapusa & North Goa",
    address: "Near Shantadurga High School, Bicholim, Goa 403504",
    lat: 15.5937,
    lng: 73.9451,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Town Center",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "Home of Goa's celebrated Kumbhar (clay artisan) heritage; the murti here is crafted entirely from river clay using ancestral techniques.",
    sourceLine: "Bicholim Ganeshotsav Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bicholim+Ganeshotsav+Goa",
    source: "official"
  },
  {
    id: "GA-PER-001",
    rank: 109,
    name: "Harmal Sarvajanik Ganeshotsav Mandal",
    area: "Arambol / Harmal",
    city: "Pernem",
    state: "Goa",
    region: "Mapusa & North Goa",
    address: "Harmal Main Cross, Arambol, Pernem, Goa 403524",
    lat: 15.6868,
    lng: 73.7049,
    status: "confirmed",
    confidence: "exact",
    pinPrecision: "Coastal Village Square",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Coastal Pernem community festival known for traditional fugdi dance, folk singing, and festive coconut sweets.",
    sourceLine: "Harmal Ganeshotsav Samiti 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Harmal+Ganeshotsav+Arambol+Goa",
    source: "official"
  },
  {
    id: "GA-PER-002",
    rank: 110,
    name: "Korgao Sarvajanik Ganeshotsav Mandal",
    area: "Corgao",
    city: "Pernem",
    state: "Goa",
    region: "Mapusa & North Goa",
    address: "Near Kamleshwar Temple, Korgao, Pernem, Goa 403512",
    lat: 15.7180,
    lng: 73.7950,
    status: "confirmed",
    confidence: "exact",
    pinPrecision: "Temple Village",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Ancient Pernem temple village celebration highlighting Goan Shigmotsav style folk rhythms and aarti.",
    sourceLine: "Korgao Ganeshotsav Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Korgao+Ganeshotsav+Pernem+Goa",
    source: "official"
  },
  {
    id: "GA-PER-003",
    rank: 111,
    name: "Sarvajanik Ganeshotsav Mandal Casarwarnem",
    area: "Casarwarnem",
    city: "Pernem",
    state: "Goa",
    region: "Mapusa & North Goa",
    address: "Casarwarnem Junction, Pernem, Goa 403512",
    lat: 15.6820,
    lng: 73.8280,
    status: "confirmed",
    confidence: "approximate",
    pinPrecision: "Pernem Highway Junction",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7 PM",
    timingDetails: "Northern border district festival celebrated with hearty Konkani hospitality and sacred devotional songs.",
    sourceLine: "Goa Directorate of Art and Culture 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Casarwarnem+Ganeshotsav+Pernem+Goa",
    source: "official"
  },

  // ==========================================
  // KARNATAKA
  // ==========================================
  // Bengaluru
  {
    id: "KA-BLR-001",
    rank: 112,
    name: "64th Bengaluru Ganesh Utsava (BGU)",
    area: "APS College Grounds, Basavanagudi",
    city: "Bengaluru",
    state: "Karnataka",
    region: "Bengaluru",
    address: "APS College Grounds, NR Colony, Basavanagudi, Bengaluru 560019",
    lat: 12.9423,
    lng: 77.5735,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Major Festival Ground",
    evidenceYear: 2026,
    aarti_times: "Pooja: 8:30 AM | Aarti: 7 PM",
    timingDetails: "Karnataka's most iconic cultural Ganeshotsav since 1962. Features top Indian classical maestros, 100% eco-friendly clay idol, and massive musical concerts.",
    sourceLine: "Bengaluru Ganesh Utsava Trust 2026 official schedule.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bengaluru+Ganesh+Utsava+Basavanagudi",
    source: "official"
  },
  {
    id: "KA-BLR-002",
    rank: 113,
    name: "Malleswaram Canara Bank Ganeshotsava",
    area: "Malleswaram",
    city: "Bengaluru",
    state: "Karnataka",
    region: "Bengaluru",
    address: "Canara Bank Grounds, 8th Main, 15th Cross, Malleswaram, Bengaluru 560003",
    lat: 13.0072,
    lng: 77.5684,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 7:30 PM",
    timingDetails: "Over 65 years of grand heritage in Malleswaram, renowned for majestic natural flower canopies, Vedic chants, and Carnatic music evenings.",
    sourceLine: "Canara Bank Recreation Club Ganeshotsava Samithi 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Malleswaram+Canara+Bank+Ganeshotsava+Bengaluru",
    source: "official"
  },
  {
    id: "KA-BLR-003",
    rank: 114,
    name: "DVG Road Gandhi Bazaar Sarvajanika Ganeshotsav",
    area: "Gandhi Bazaar, Basavanagudi",
    city: "Bengaluru",
    state: "Karnataka",
    region: "Bengaluru",
    address: "DVG Road, Gandhi Bazaar Circle, Basavanagudi, Bengaluru 560004",
    lat: 12.9448,
    lng: 77.5712,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Heritage Street Pandal",
    evidenceYear: 2026,
    aarti_times: "Aarti: 9 AM | 8 PM",
    timingDetails: "South Bengaluru's bustling festive epicenter on DVG Road, adorned with fragrant jasmine garlands and traditional street illuminations.",
    sourceLine: "Gandhi Bazaar Merchants Association 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Gandhi+Bazaar+Ganeshotsav+Bengaluru",
    source: "official"
  },
  {
    id: "KA-BLR-004",
    rank: 115,
    name: "Sree Panchamukha Ganesha Temple",
    area: "Mahalakshmi Layout",
    city: "Bengaluru",
    state: "Karnataka",
    region: "Bengaluru",
    address: "1st Main Road, Mahalakshmi Layout, Bengaluru 560086",
    lat: 13.0169,
    lng: 77.5458,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 7 AM | 12:30 PM | 7:30 PM",
    timingDetails: "Revered shrine housing an imposing 30-foot five-faced (Panchamukha) golden Ganesha representing the five cosmic elements.",
    sourceLine: "Panchamukha Temple Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Panchamukha+Ganesha+Temple+Mahalakshmi+Layout",
    source: "official"
  },
  {
    id: "KA-BLR-005",
    rank: 116,
    name: "Dodda Ganapathi Temple, Basavanagudi",
    area: "Bull Temple Road, Basavanagudi",
    city: "Bengaluru",
    state: "Karnataka",
    region: "Bengaluru",
    address: "Bull Temple Road, Basavanagudi, Bengaluru 560004",
    lat: 12.9428,
    lng: 77.5682,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Historic Monolith Shrine",
    evidenceYear: 2026,
    aarti_times: "Aarti: 6:30 AM | 1 PM | 8 PM",
    timingDetails: "Ancient monolith Ganesha carved from a single boulder (18 ft high, 16 ft wide) established by Kempe Gowda I. Famous for the Benne Alankara (butter decor).",
    sourceLine: "Muzrai Department & Temple Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Dodda+Ganapathi+Temple+Basavanagudi",
    source: "official"
  },

  // Karnataka — Belagavi (Belgaum - Second largest Ganeshotsav in India)
  {
    id: "KA-BEL-001",
    rank: 117,
    name: "Belgaum cha Bhagyavidhata",
    area: "Bhagya Nagar, Angol",
    city: "Belagavi",
    state: "Karnataka",
    region: "Belagavi",
    address: "1st Cross, Bhagya Nagar, Angol Main Road, Belagavi 590006",
    lat: 15.8421,
    lng: 74.4977,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Venue-level",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "The crown jewel of Belagavi Ganeshotsav. Known for massive royal palace replicas and around-the-clock darshan queues drawing visitors from MH and KA.",
    sourceLine: "Belgaum cha Bhagyavidhata Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Belgaum+cha+Bhagyavidhata+Angol",
    source: "official"
  },
  {
    id: "KA-BEL-002",
    rank: 118,
    name: "Shahapur Sarvajanik Ganeshotsav",
    area: "Shahapur Market",
    city: "Belagavi",
    state: "Karnataka",
    region: "Belagavi",
    address: "Old Market, Shahapur, Belagavi 590003",
    lat: 15.8395,
    lng: 74.5122,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Historic Market Square",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8:30 PM",
    timingDetails: "Historic weaving community festival dating back to the late 1800s, renowned for intricate animated tableaux (Chitra-Pradarshan) depicting Indian epics.",
    sourceLine: "Shahapur Central Ganeshotsav Samithi 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Shahapur+Ganeshotsav+Belgaum",
    source: "official"
  },
  {
    id: "KA-BEL-003",
    rank: 119,
    name: "Maruti Galli & Ganpat Galli Sarvajanik Mandal",
    area: "Maruti Galli / Ganpat Galli",
    city: "Belagavi",
    state: "Karnataka",
    region: "Belagavi",
    address: "Ganpat Galli, Raviwar Peth, Belagavi 590001",
    lat: 15.8562,
    lng: 74.5128,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Historic Street Corner",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "The oldest documented public Ganeshotsav in Karnataka, inaugurated during Lokmanya Tilak's historic visit to Belgaum.",
    sourceLine: "Ganpat Galli Ganeshotsav Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ganpat+Galli+Ganeshotsav+Belagavi",
    source: "official"
  },
  {
    id: "KA-BEL-004",
    rank: 120,
    name: "Camp Sarvajanik Ganeshotsav",
    area: "Camp",
    city: "Belagavi",
    state: "Karnataka",
    region: "Belagavi",
    address: "High Street, Camp, Belagavi 590009",
    lat: 15.8524,
    lng: 74.5035,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Cantonment Ground",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8 PM",
    timingDetails: "Renowned cantonment celebration known for patriotic themes, grand floral pandal sets, and harmonious multi-community volunteer teams.",
    sourceLine: "Camp Ganeshotsav Samithi 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Camp+Ganeshotsav+Belgaum",
    source: "official"
  },

  // Karnataka — Hubballi-Dharwad
  {
    id: "KA-HUB-001",
    rank: 121,
    name: "Hubballi Idgah Ground Ganeshotsava",
    area: "Idgah Ground",
    city: "Hubballi",
    state: "Karnataka",
    region: "Hubballi-Dharwad",
    address: "Idgah Maidan, Court Circle, Hubballi 580029",
    lat: 15.3647,
    lng: 75.1239,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Maidan Grounds",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 8 PM",
    timingDetails: "High-profile festival attracting lakhs across North Karnataka, featuring solemn vedic rituals and massive devotional assemblies.",
    sourceLine: "Rani Chennamma Maidan Gajanan Utsav Samithi 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Hubballi+Idgah+Maidan+Ganeshotsav",
    source: "official"
  },
  {
    id: "KA-HUB-002",
    rank: 122,
    name: "Durgadbail Sarvajanika Ganeshotsava",
    area: "Durgadbail Circle",
    city: "Hubballi",
    state: "Karnataka",
    region: "Hubballi-Dharwad",
    address: "Durgadbail, Old Hubli, Hubballi 580020",
    lat: 15.3524,
    lng: 75.1418,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Commercial Circle",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8:30 PM",
    timingDetails: "The commercial heart of Hubballi's Ganesh festival, celebrated continuously for over seven decades with magnificent lighting tunnels.",
    sourceLine: "Durgadbail Vyapari Ganesh Mandal 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Durgadbail+Ganeshotsav+Hubballi",
    source: "official"
  },
  {
    id: "KA-HUB-003",
    rank: 123,
    name: "Maratha Galli Sarvajanik Ganeshotsav",
    area: "Maratha Galli",
    city: "Hubballi",
    state: "Karnataka",
    region: "Hubballi-Dharwad",
    address: "Maratha Galli, Durgadbail, Hubballi 580020",
    lat: 15.3567,
    lng: 75.1382,
    status: "confirmed",
    confidence: "exact",
    pinPrecision: "Historic Street Corner",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 8 PM",
    timingDetails: "Historical mandal known for traditional Dhol beats and patriotic tributes during the immersion rally.",
    sourceLine: "Hubballi Police & Municipal 2026 approved festival list.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Maratha+Galli+Ganeshotsav+Hubballi",
    source: "official"
  },

  // Karnataka — Mangaluru & Coastal Karnataka
  {
    id: "KA-MNG-001",
    rank: 124,
    name: "Sri Siddhi Vinayaka Sarvajanika Sri Ganeshotsava",
    area: "Omkara Nagar, Bunts Hostel",
    city: "Mangaluru",
    state: "Karnataka",
    region: "Mangaluru & Coast",
    address: "Bunts Hostel Circle, Kadri, Mangaluru 575003",
    lat: 12.8756,
    lng: 74.8437,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Auditorium Grounds",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8 AM | 12:30 PM | 8 PM",
    timingDetails: "Mangaluru's premier 5-day celebration. Famous for massive coastal Anna Santharpane (serving over 40,000 devotees daily) and Yakshagana dance-dramas.",
    sourceLine: "Bunts Hostel Sri Ganeshotsava Samithi 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bunts+Hostel+Ganeshotsav+Mangalore",
    source: "official"
  },
  {
    id: "KA-MNG-002",
    rank: 125,
    name: "Sanghaniketan Sarvajanika Ganeshotsava",
    area: "Prathapa Nagara, Mannagudda",
    city: "Mangaluru",
    state: "Karnataka",
    region: "Mangaluru & Coast",
    address: "Sanghaniketan, Mannagudda, Mangaluru 575003",
    lat: 12.8821,
    lng: 74.8365,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Civic Complex",
    evidenceYear: 2026,
    aarti_times: "Aarti: 8:30 AM | 7:30 PM",
    timingDetails: "78th year of sacred celebration in coastal Karnataka. Emphasizes strict Vedic rituals, Vedic chanting, and eco-friendly natural clay murtis.",
    sourceLine: "Sarvajanika Ganeshotsava Samithi Sanghaniketan 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Sanghaniketan+Ganeshotsav+Mangalore",
    source: "official"
  },
  {
    id: "KA-MNG-003",
    rank: 126,
    name: "Mithra Mandali Sarvajanika Ganeshotsava",
    area: "Temple Square, Car Street",
    city: "Mangaluru",
    state: "Karnataka",
    region: "Mangaluru & Coast",
    address: "Car Street, near Venkataramana Temple, Mangaluru 575001",
    lat: 12.8698,
    lng: 74.8421,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Temple Square",
    evidenceYear: 2026,
    aarti_times: "Aarti: 9 AM | 8 PM",
    timingDetails: "70th year of community celebration in the historic Car Street precinct, accompanied by traditional chende drums and grand procession.",
    sourceLine: "Mithra Mandali Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Mithra+Mandali+Ganeshotsav+Mangalore",
    source: "official"
  },
  {
    id: "KA-UK-001",
    rank: 127,
    name: "Sri Mahaganapathi Temple, Idagunji",
    area: "Idagunji",
    city: "Honnavar",
    state: "Karnataka",
    region: "Mangaluru & Coast",
    address: "Idagunji, Honnavar Taluk, Uttara Kannada District 581423",
    lat: 14.3008,
    lng: 74.4754,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Ancient Devasthana",
    evidenceYear: 2026,
    aarti_times: "Aarti: 6 AM | 12:30 PM | 7:30 PM",
    timingDetails: "1500-year-old Dvibhuja (two-handed) standing Ganapathi shrine holding Modaka and Padma. Draws over a million pilgrims during festival months.",
    sourceLine: "Idagunji Devasthana Trust 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Idagunji+Maha+Ganapathi+Temple",
    source: "official"
  },
  {
    id: "KA-UK-002",
    rank: 128,
    name: "Maha Ganapati Temple, Gokarna",
    area: "Gokarna Main Beach Road",
    city: "Gokarna",
    state: "Karnataka",
    region: "Mangaluru & Coast",
    address: "Near Mahabaleshwar Temple, Gokarna, Uttara Kannada District 581326",
    lat: 14.5427,
    lng: 74.3168,
    status: "editor_verified",
    confidence: "exact",
    pinPrecision: "Sacred Temple Sanctum",
    evidenceYear: 2026,
    aarti_times: "Aarti: 6 AM | 12 PM | 7 PM",
    timingDetails: "Mythological shrine marking where boy Ganesha tricked Ravana to place down the sacred Atma-Linga. Devotees visit this shrine before Mahabaleshwar.",
    sourceLine: "Gokarna Devasthanam 2026.",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Maha+Ganapati+Temple+Gokarna",
    source: "official"
  }
];

// ==========================================
// REGIONAL MODAK & FESTIVE SWEET STOPS
// ==========================================
window.REGIONAL_MODAK_STOPS_DATA = [
  // Maharashtra — Pune & Nagpur
  {
    name: "Chitale Bandhu Mithaiwale",
    area: "Bajirao Road",
    city: "Pune",
    state: "Maharashtra",
    address: "777, Sadashiv Peth, Bajirao Road, Pune 411030",
    notableFor: "Legendary steamed Ukadiche Modak, Mawa Modak, and signature festive boxes",
    lat: 18.5132,
    lng: 73.8519,
    type: "shop"
  },
  {
    name: "Kaka Halwai Sweet Centre",
    area: "Budhwar Peth / Laxmi Road",
    city: "Pune",
    state: "Maharashtra",
    address: "538, Budhwar Peth, Laxmi Road, Pune 411002",
    notableFor: "Over 130 years of traditional Kesari Peda, Kaju Modak, and fresh steamed festive modak",
    lat: 18.5168,
    lng: 73.8569,
    type: "shop"
  },
  {
    name: "Mithas Sweets & Savouries",
    area: "Prabhat Road",
    city: "Pune",
    state: "Maharashtra",
    address: "Lane 4, Prabhat Road, Erandwane, Pune 411004",
    notableFor: "Artisanal handcrafted saffron-coconut and dry fruit modaks",
    lat: 18.5115,
    lng: 73.8340,
    type: "shop"
  },
  {
    name: "Ksheer Sagar Sweets",
    area: "Sitabuldi",
    city: "Nagpur",
    state: "Maharashtra",
    address: "Station Road, Sitabuldi, Nagpur 440012",
    notableFor: "Vidarbha's top destination for pure ghee mawa modaks and prasad laddus",
    lat: 21.1458,
    lng: 79.0833,
    type: "shop"
  },

  // Goa — Panaji & Margao
  {
    name: "Cafe Tato",
    area: "Church Square",
    city: "Panaji",
    state: "Goa",
    address: "Near Municipal Garden, Church Square, Panaji, Goa 403001",
    notableFor: "Goa's historic heritage cafe (est. 1913) serving freshly steamed coconut-jaggery modaks (Nevryo)",
    lat: 15.4988,
    lng: 73.8262,
    type: "shop"
  },
  {
    name: "Cafe Real",
    area: "MG Road",
    city: "Panaji",
    state: "Goa",
    address: "MG Road, Altinho Junction, Panaji, Goa 403001",
    notableFor: "Over a century of authentic Goan festive snacks, puran poli, and traditional festive modaks",
    lat: 15.4975,
    lng: 73.8245,
    type: "shop"
  },
  {
    name: "Mohanbandh Sweets",
    area: "Municipal Market",
    city: "Margao",
    state: "Goa",
    address: "Municipal Market Lane, Margao, Goa 403601",
    notableFor: "South Goa's premier traditional sweet house famous for festival modaks, khaje, and laddoos",
    lat: 15.2745,
    lng: 73.9575,
    type: "shop"
  },
  {
    name: "Cremeux Bakery & Confectionery",
    area: "MG Road",
    city: "Panaji",
    state: "Goa",
    address: "Opposite Azad Maidan, Panaji, Goa 403001",
    notableFor: "Modern Goan cashew-nut and chocolate fusion festive modaks",
    lat: 15.4962,
    lng: 73.8251,
    type: "shop"
  },

  // Karnataka — Bengaluru, Belagavi & Mangaluru
  {
    name: "Kanti Sweets",
    area: "KG Road & Basavanagudi",
    city: "Bengaluru",
    state: "Karnataka",
    address: "12, DVG Road, Gandhi Bazaar, Basavanagudi, Bengaluru 560004",
    notableFor: "Legendary Karnataka confectioner since 1957, renowned for Kozhukattai, steamed modak, and Badam Halwa",
    lat: 12.9442,
    lng: 77.5718,
    type: "shop"
  },
  {
    name: "Anand Sweets & Savouries",
    area: "Commercial Street",
    city: "Bengaluru",
    state: "Karnataka",
    address: "8, Commercial Street, Tasker Town, Bengaluru 560001",
    notableFor: "Artisanal Royal Dry Fruit Modak, Motichoor Modak, and festival gift boxes",
    lat: 12.9818,
    lng: 77.6085,
    type: "shop"
  },
  {
    name: "Asha Sweet Center",
    area: "Malleswaram",
    city: "Bengaluru",
    state: "Karnataka",
    address: "Sampige Road, 8th Cross, Malleswaram, Bengaluru 560003",
    notableFor: "Beloved 70-year-old Malleswaram sweet shop renowned for festive Ganesha Habba hampers and coconut modaks",
    lat: 13.0035,
    lng: 77.5710,
    type: "shop"
  },
  {
    name: "Purohit Sweets",
    area: "Camp",
    city: "Belagavi",
    state: "Karnataka",
    address: "Kadolkar Galli, Camp, Belagavi 590001",
    notableFor: "Belagavi's iconic sweet destination; world-famous authentic Belgaum Kunda and festival modaks",
    lat: 15.8532,
    lng: 74.5041,
    type: "shop"
  },
  {
    name: "Sri Krishna Sweets",
    area: "Mallikatte / Kadri",
    city: "Mangaluru",
    state: "Karnataka",
    address: "Mallikatte Circle, Kadri, Mangaluru 575002",
    notableFor: "Authentic coastal Karnataka Ganesha pooja sweets, steamed kozhukattai, and Mysore Pak",
    lat: 12.8722,
    lng: 74.8490,
    type: "shop"
  }
];

// Backwards compatibility aliases
window.regionalPandals = window.REGIONAL_PANDALS_DATA;
window.regionalModakStops = window.REGIONAL_MODAK_STOPS_DATA;
